import sqlite3
conn = sqlite3.connect('data/app.db')
c = conn.cursor()
c.execute("SELECT name FROM sqlite_master WHERE type='table'")
print('Tables:', [t[0] for t in c.fetchall()])
c.execute('SELECT COUNT(*) FROM artifacts')
print('Artifacts:', c.fetchone()[0])
c.execute('SELECT COUNT(*) FROM users')
print('Users:', c.fetchone()[0])
c.execute('SELECT COUNT(*) FROM chat_sessions')
print('Sessions:', c.fetchone()[0])
c.execute('SELECT COUNT(*) FROM chat_messages')
print('Messages:', c.fetchone()[0])
conn.close()
