// 示例文物数据
const sampleArtifacts = [
  {
    id: 1,
    name: '四羊方尊',
    description: '商代晚期青铜礼器，出土于湖南宁乡，因器身四面各有一只羊而得名，是中国商代青铜文化的代表作之一。',
    category: '青铜器',
    era: '商代',
    location: '湖南宁乡',
    image_url: 'https://pic.baike.soso.com/ugc/baikepic2/0/20200722144851-1624292484.jpg/800',
    dating: '公元前13-12世纪',
    material: '青铜',
    dimensions: '高43厘米，口长23厘米，宽22厘米',
    collection: '中国国家博物馆',
    tags: ['礼器', '青铜', '兽面纹']
  },
  {
    id: 2,
    name: '司母戊鼎',
    description: '商代晚期青铜器，出土于河南安阳，是中国现存最大的商代青铜鼎，也被称为"后母戊鼎"，重达832.84千克。',
    category: '青铜器',
    era: '商代',
    location: '河南安阳',
    image_url: 'https://pic.baike.soso.com/ugc/baikepic2/0/20160928161539-626487870.jpg/800',
    dating: '公元前13-12世纪',
    material: '青铜',
    dimensions: '高133厘米，口径110厘米',
    collection: '中国国家博物馆',
    tags: ['礼器', '青铜', '鼎', '最大']
  },
  {
    id: 3,
    name: '毛公鼎',
    description: '西周晚期青铜器，铭文497字，记述了周厉王赐爵赏给毛公的场景，是研究西周政治、礼制的重要资料。',
    category: '青铜器',
    era: '西周',
    location: '陕西岐山',
    image_url: 'https://pic.baike.soso.com/ugc/baikepic2/0/20160928161540-1023927129.jpg/800',
    dating: '公元前9-8世纪',
    material: '青铜',
    dimensions: '高53.8厘米，口径47.9厘米',
    collection: '台北故宫博物院',
    tags: ['礼器', '青铜', '鼎', '铭文']
  },
  {
    id: 4,
    name: '三彩骆驼',
    description: '唐代三彩陶器，形象生动，彩釉艳丽，反映了唐代丝绸之路文化交流的盛况。',
    category: '陶器',
    era: '唐代',
    location: '陕西西安',
    image_url: 'https://pic.baike.soso.com/ugc/baikepic2/0/20160919201044-960279990.jpg/800',
    dating: '公元7-8世纪',
    material: '陶器',
    dimensions: '高70厘米，长52厘米',
    collection: '陕西历史博物馆',
    tags: ['三彩', '陶器', '骆驼', '丝绸之路']
  },
  {
    id: 5,
    name: '清明上河图',
    description: '北宋张择端创作的绢本设色画卷，长528.7厘米，描绘了北宋都城汴京的繁华景象，反映了当时的经济、文化、社会风貌。',
    category: '书画',
    era: '北宋',
    location: '河南开封',
    image_url: 'https://pic.baike.soso.com/ugc/baikepic2/0/20160919145839-574252399.jpg/800',
    dating: '公元12世纪',
    material: '绢本设色',
    dimensions: '24.8厘米×528.7厘米',
    collection: '北京故宫博物院',
    tags: ['绘画', '风俗画', '城市生活']
  },
  {
    id: 6,
    name: '和氏璧',
    description: '春秋战国时期的传奇玉璧，相传为卞和献给楚文王的美玉，后成为传国玉玺的原料。',
    category: '玉器',
    era: '战国',
    location: '湖北荆州',
    image_url: '',
    dating: '公元前5-3世纪',
    material: '和田玉',
    dimensions: '不详',
    collection: '失传',
    tags: ['玉璧', '传国玉玺', '传说']
  },
  {
    id: 7,
    name: '曾侯乙编钟',
    description: '战国早期曾国高级贵族墓出土的青铜编钟，由65件钟组成，音律精确，铭文丰富，是中国古代乐器的杰出代表。',
    category: '青铜器',
    era: '战国',
    location: '湖北随州',
    image_url: 'https://pic.baike.soso.com/ugc/baikepic2/0/ori-20220629154405-1056114104_jpg_800_0_0.jpg/800',
    dating: '公元前5世纪',
    material: '青铜',
    dimensions: '最大钟高152.3厘米',
    collection: '湖北省博物馆',
    tags: ['乐器', '青铜', '编钟']
  },
  {
    id: 8,
    name: '兵马俑',
    description: '秦始皇陵出土的陶质彩绘武士俑，共有8000多个真人大小的陶俑，再现了秦代军队的雄壮场面。',
    category: '陶器',
    era: '秦代',
    location: '陕西西安',
    image_url: 'https://pic.baike.soso.com/ugc/baikepic2/0/20200514124542-1671564116.jpg/800',
    dating: '公元前3世纪',
    material: '陶器',
    dimensions: '平均高180厘米',
    collection: '秦始皇帝陵博物院',
    tags: ['陶俑', '军阵', '彩绘', '世界文化遗产']
  },
  {
    id: 9,
    name: '莫高窟壁画',
    description: '敦煌莫高窟保存的壁画，创作时间跨越近千年，总面积达45000平方米，是世界上现存规模最大、内容最丰富的佛教艺术宝库。',
    category: '壁画',
    era: '多朝代',
    location: '甘肃敦煌',
    image_url: 'https://pic.baike.soso.com/ugc/baikepic2/0/20160919114853-390135760.jpg/800',
    dating: '公元4-14世纪',
    material: '壁画',
    dimensions: '总面积45000平方米',
    collection: '敦煌研究院',
    tags: ['佛教艺术', '壁画', '石窟', '世界文化遗产']
  },
  {
    id: 10,
    name: '富春山居图',
    description: '元代黄公望创作的山水画，原作分为《剩山图》和《无用师卷》两部分，分别藏于浙江博物馆和台北故宫博物院。',
    category: '书画',
    era: '元代',
    location: '浙江杭州',
    image_url: 'https://pic.baike.soso.com/ugc/baikepic2/0/20220212112437-1242962124_jpg_814_402_57271.jpg/800',
    dating: '公元1350年',
    material: '纸本水墨',
    dimensions: '31.8厘米×689.3厘米',
    collection: '浙江省博物馆/台北故宫博物院',
    tags: ['山水画', '水墨', '文人画']
  }
];

module.exports = sampleArtifacts;
